from .middleware import JWTAuthMiddleware
from .jwks import verify_token, get_jwks_keys
from .resource_metadata import register_resource_metadata
from .enterprise import (
    AuditEventV1,
    AuthIntegration,
    AuthProviderKind,
    DeploymentMode,
    EnterpriseSubject,
    SealfleetResourceAdapter,
    MarketplaceIdentityHook,
    Organization,
    PolicyDecisionEnvelope,
    PolicyResource,
    PrincipalType,
    RoleGrant,
    ScimProvisioningContract,
    SealedHandleDescriptor,
    ServiceIdentity,
    SessionDescriptor,
    TeamGroup,
    Tenant,
    enterprise_contract_v1,
)

__all__ = [
    "JWTAuthMiddleware",
    "verify_token",
    "get_jwks_keys",
    "register_resource_metadata",
    "AuditEventV1",
    "AuthIntegration",
    "AuthProviderKind",
    "DeploymentMode",
    "EnterpriseSubject",
    "SealfleetResourceAdapter",
    "MarketplaceIdentityHook",
    "Organization",
    "PolicyDecisionEnvelope",
    "PolicyResource",
    "PrincipalType",
    "RoleGrant",
    "ScimProvisioningContract",
    "SealedHandleDescriptor",
    "ServiceIdentity",
    "SessionDescriptor",
    "TeamGroup",
    "Tenant",
    "enterprise_contract_v1",
]
__version__ = "0.2.0"
