-- Migration: Create api_keys table for router authentication
-- Run: psql postgresql://admin:admin@localhost:54323/mcpfinder < scripts/001_create_api_keys.sql

CREATE TABLE IF NOT EXISTS api_keys (
    api_key TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    is_active BOOLEAN DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_api_keys_tenant ON api_keys(tenant_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_active ON api_keys(is_active) WHERE is_active = true;

-- The router enforces per-action permissions from api_keys.action_permissions
-- (see runtime/router.py:_authorize_action). The column is added by later
-- migrations; ensure it exists so this bootstrap is self-contained.
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS action_permissions TEXT[];
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS allow_identity_delegation BOOLEAN NOT NULL DEFAULT false;

-- NOTE: the local-dev operator key is NOT hardcoded here anymore. docker-compose's
-- `migrate` step seeds it from a PER-DEPLOYMENT random value generated by the
-- `keygen` service (/keys/runtime-api-key); the portal presents the same value.
-- This avoids shipping a known, world-readable delegation-capable key.
--
-- The seeded key grants a least-privilege "agent operator" action set
-- (pipeline.invoke, agent.invoke, agent.register, mcp.server.register,
-- registry.export, registry.import) and deliberately EXCLUDES privileged actions
-- (policy.admin, credential.*, sealed_handle.*, audit.read). allow_identity_delegation
-- lets the portal pass the logged-in user/tenant via X-McpFinder-* headers so audit
-- rows reflect the real user — safe now that the key is unique per deployment.
--
-- To seed a key when running this file standalone, insert your OWN generated value:
--   INSERT INTO api_keys (api_key, tenant_id, name, is_active, action_permissions, allow_identity_delegation)
--   VALUES ('<your-random-key>', 'local-dev', 'Local Development Key', true,
--           ARRAY['pipeline.invoke','agent.invoke','agent.register','mcp.server.register','registry.export','registry.import'], true)
--   ON CONFLICT (api_key) DO UPDATE SET is_active = true;
